Repository jenkinsci/scm-api-plugin, pull requests merged in 2022-01, with the labels that each got.

#104 EOL JSR 305
  src/main/java/jenkins/scm/api/MethodUtils.java
  src/main/java/jenkins/scm/impl/SCM2TransientActionFactory.java
  src/test/java/jenkins/scm/impl/mock/MockSCM.java
Labels: dependencies

#107 Update parent, baseline, BOM
  pom.xml
  src/test/java/jenkins/scm/impl/SingleSCMNavigatorTest.java
  src/test/java/jenkins/scm/impl/SingleSCMSourceTest.java
Labels: dependencies

#95 Deprecating some `SCMNavigatorDescriptor` methods that are no longer called
  src/main/java/jenkins/scm/api/SCMNavigatorDescriptor.java
Labels: documentation

#108 Enable CD
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: chore

#111 Typo in #108
  .github/release-drafter.yml
Labels: chore
